apiVersion: v1
kind: Service
metadata:
  name: web-appfe
  namespace: web-app-frontend
spec:
  selector:
    app: web-appfe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
