apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-appfe
  namespace: web-app-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-appfe
  template:
    metadata:
      labels:
        app: web-appfe
    spec:
      containers:
      - name: web-appfe
        image: [acr-name-here].azurecr.io/[docker-image-name-here]:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-registry-secret
