apiVersion: v1
kind: Service
metadata:
  name: hobbitappfe
  namespace: hobbitapp-frontend
spec:
  selector:
    app: hobbitappfe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
